
export  const EVENT_REQUEST = 'EVENT_REQUEST'
export  const EVENT_SUCCESS = 'EVENT_SUCCESS'
export  const EVENT_FAIL = 'EVENT_FAIL'


export  const PURCHASE_EVENT_REQUEST = 'PURCHASE_EVENT_REQUEST'
export  const PURCHASE_EVENT_SUCCESS = 'PURCHASE_EVENT_SUCCESS'
export  const PURCHASE_EVENT_FAIL = 'PURCHASE_EVENT_FAIL'
