# Generated by Django 4.0.1 on 2022-03-18 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('code', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=75, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookDate', models.DateField()),
                ('customerCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
            ],
            options={
                'unique_together': {('cookDate', 'customerCode')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('dateRequested', models.DateField()),
                ('totalNet', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('totalVat', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('live', 'Live'), ('completed', 'Completed'), ('edit', 'For Editing')], default='edit', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('code', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=75, null=True)),
                ('quantityInStock', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quantityOutstanding', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('unit', models.CharField(choices=[('kg', 'Kg'), ('ltr', 'Ltr'), ('each', 'Each')], default='each', max_length=5)),
                ('stockType', models.CharField(choices=[('COM', 'COM'), ('ING/PACK', 'ING/PACK'), ('DSI', 'DSI')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('code', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('addressLine1', models.CharField(blank=True, max_length=100, null=True)),
                ('addressLine2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('postCode', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockToBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratioToStock', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('taxCode', models.CharField(choices=[('exempt', 'Exempt'), ('standardRate', 'Standard Rate'), ('zeroRated', 'Zero Rated')], default='zeroRated', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dateModified', models.DateField(auto_now=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toBuy', to='base.stockitem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.supplier')),
            ],
            options={
                'ordering': ('code',),
                'unique_together': {('code', 'supplier')},
            },
        ),
        migrations.AddField(
            model_name='stockitem',
            name='defaultSupplier',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.supplier'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('goodsRecieved', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('conversionRate', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('purchaseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='base.purchaseorder')),
                ('stockCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.stocktobuy')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.supplier'),
        ),
        migrations.CreateModel(
            name='EventLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='base.event')),
                ('mealCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.stockitem')),
            ],
            options={
                'unique_together': {('mealCode', 'eventID')},
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comQuantity', models.DecimalField(decimal_places=6, max_digits=10)),
                ('kitchen', models.CharField(blank=True, choices=[('Hot', 'Hot'), ('Cold', 'Cold'), ('Packing', 'Packing')], max_length=20, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('bomCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='base.stockitem')),
                ('comCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='com', to='base.stockitem')),
            ],
            options={
                'unique_together': {('bomCode', 'comCode')},
            },
        ),
    ]
