# Generated by Django 4.0.1 on 2022-03-25 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=50)),
                ('dateUploaded', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='packID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.pack'),
            preserve_default=False,
        ),
    ]
