# Generated by Django 4.0.1 on 2022-03-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_pack_event_packid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='person',
            field=models.CharField(max_length=100),
        ),
    ]
