# Generated by Django 4.0.1 on 2022-03-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_pack_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
