# Generated by Django 4.0.1 on 2022-03-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_pack_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktobuy',
            name='codeForSupplier',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stocktobuy',
            name='leadTime',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stocktobuy',
            name='purchaseUnit',
            field=models.CharField(default='case', max_length=20),
            preserve_default=False,
        ),
    ]
