# Generated by Django 4.0.1 on 2022-03-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_stocktobuy_codeforsupplier_stocktobuy_leadtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktobuy',
            name='codeForSupplier',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
