# Generated by Django 4.0.1 on 2022-03-27 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_stocktobuy_codeforsupplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseDate', models.DateField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='quantityInStock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='quantityOutstanding',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='PurchaseEventLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderQuantity', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.stockitem')),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='base.purchaseevent')),
            ],
            options={
                'unique_together': {('code', 'eventID')},
            },
        ),
    ]
