# Generated by Django 4.0.1 on 2022-03-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_purchaseevent_alter_stockitem_quantityinstock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseeventline',
            name='initialQuantityDemanded',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
