# Generated by Django 4.0.1 on 2022-04-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_purchaseeventline_initialquantitydemanded'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='unconvertedQuantity',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
