# Generated by Django 4.0.1 on 2022-04-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_purchaseorderline_unconvertedquantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderline',
            name='goodsRecieved',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=8, null=True),
        ),
    ]
