# Generated by Django 4.0.1 on 2022-04-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_purchaseorderline_goodsrecieved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('completed', 'Completed'), ('edit', 'For Editing'), ('outstanding', 'Outstanding')], default='edit', max_length=20),
        ),
    ]
