# Generated by Django 4.0.1 on 2022-04-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktobuy',
            name='codeForSupplier',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
