# Generated by Django 4.0.1 on 2022-04-18 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_stocktobuy_codeforsupplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderline',
            name='stockCode',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='base.stocktobuy'),
            preserve_default=False,
        ),
    ]
