# Generated by Django 4.0.1 on 2022-04-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_purchaseorderline_goodsrecieved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderline',
            name='goodsRecieved',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
    ]
