# Generated by Django 4.0.1 on 2022-04-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_purchaseorderline_goodsrecieved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktobuy',
            name='ratioToStock',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=8),
        ),
    ]
