# Generated by Django 4.0.1 on 2022-04-22 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_stocktobuy_ratiotostock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseorderline',
            unique_together={('stockCode', 'purchaseID')},
        ),
    ]
