# Generated by Django 4.0.1 on 2022-04-26 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_purchaseorderline_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('complete', 'Complete')], default='live', max_length=20),
        ),
        migrations.CreateModel(
            name='ReductionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('wastage', 'Wastage'), ('production', 'Production')], max_length=20)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.stockitem')),
            ],
        ),
    ]
