# Generated by Django 4.0.1 on 2022-04-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_reductionrequest_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReductionRequest',
            new_name='GoodsOut',
        ),
    ]
