# Generated by Django 4.0.1 on 2022-05-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_rename_reductionrequest_goodsout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktobuy',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
        migrations.AlterField(
            model_name='stocktobuy',
            name='ratioToStock',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=13),
        ),
    ]
