# Generated by Django 4.0.1 on 2022-05-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_stocktobuy_price_alter_stocktobuy_ratiotostock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('Ltr', 'Ltr'), ('Each', 'Each')], default='each', max_length=5),
        ),
    ]
