# Generated by Django 4.0.1 on 2022-06-11 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_purchaseorder_totalnet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='defaultSupplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.supplier'),
        ),
    ]
