# Generated by Django 4.0.1 on 2022-06-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_stockitem_defaultsupplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='productGroup',
            field=models.CharField(blank=True, choices=[('meal', 'meal'), ('WIP', 'WIP'), ('fresh', 'fresh'), ('frozen', 'frozen'), ('dry', 'dry'), ('kitchen dry', 'kitchen dry'), ('deadstock frz', 'deadstock frz'), ('equipment', 'equipment'), ('meat', 'meat'), ('cold kitchen', 'cold kitchen'), ('hot kitchen', 'hot kitchen'), ('chemical', 'chemical'), ('consumable', 'consumable'), ('dessert', 'dessert')], max_length=50, null=True),
        ),
    ]
