# Generated by Django 4.0.1 on 2022-06-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_stockitem_productgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('Ltr', 'Ltr'), ('Each', 'Each'), ('Case', 'Case')], default='each', max_length=5),
        ),
    ]
