# Generated by Django 4.0.1 on 2022-06-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_stockitem_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='productGroup',
        ),
    ]
