# Generated by Django 4.0.1 on 2022-06-29 08:48

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_remove_stockitem_productgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('completed', 'Completed'), ('edit', 'For Editing'), ('outstanding', 'Outstanding')], default='edit', max_length=20, validators=[base.models.PurchaseOrder.validate_status]),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='stockType',
            field=models.CharField(choices=[('COM', 'COM'), ('ING/PACK', 'ING/PACK'), ('DSI', 'DSI')], max_length=10, validators=[base.models.StockItem.validate_type]),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('Ltr', 'Ltr'), ('Each', 'Each')], default='each', max_length=5, validators=[base.models.StockItem.validate_uom]),
        ),
    ]
