# Generated by Django 4.0.1 on 2022-07-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_purchaseorder_status_alter_stockitem_stocktype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='quantityInStock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='quantityOutstanding',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=30),
        ),
    ]
